/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
`DEFINE_CUSTOM_INSTR(DIAG_LD_ICT, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_ICD, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_DCT, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_DCD, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_MMUP, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_BYP, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_DST, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_TLB, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_BRA, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_LRU, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_ITCM, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_DTCM, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_PMP, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LD_XTND, I_FORMAT, LOAD, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_ICT, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_ICD, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_DCT, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_DCD, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_MMUP, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_BYP, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_DST, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_TLB, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_BRA, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_LRU, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_ITCM, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_DTCM, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_PMP, I_FORMAT, LOAD, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_LW_XTND, I_FORMAT, LOAD, RV32NOELV)

// STORE INSTRUCTIONS
`DEFINE_CUSTOM_INSTR(DIAG_SD_ICT, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_ICD, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_DCT, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_DCD, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_MMUP, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_BYP, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_DST, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_TLB, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_BRA, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_LRU, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_ITCM, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_DTCM, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_PMP, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SD_XTND, I_FORMAT, STORE, RV64NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_ICT, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_ICD, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_DCT, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_DCD, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_MMUP, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_BYP, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_DST, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_TLB, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_BRA, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_LRU, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_ITCM, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_DTCM, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_PMP, I_FORMAT, STORE, RV32NOELV)
`DEFINE_CUSTOM_INSTR(DIAG_SW_XTND, I_FORMAT, STORE, RV32NOELV)
